name: autorun

on:
  workflow_dispatch:
  schedule:
    # 5分钟运行一次
    - cron: '0/5 * * * *'
    

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Check if service is running
      id: check_service
      run: |
        a=$(curl -I -s https://vp.prdnb.us.kg|head -1|sed 's/ /\n/g' | sed -n '2p' | tr -d '\r\n')
        echo $a
        if [ $a = '426' ];then
          echo "service_status=running" >> $GITHUB_ENV
        else
          echo "service_status=not_running" >> $GITHUB_ENV
        fi

    - name: Run script on remote server if service is not running
      if: env.service_status == 'not_running'
      run: ssh -o StrictHostKeyChecking=no wanggz@s8.serv00.com "/home/wanggz/run.sh" #这里改成你的用户名@你的ssh服务器地址
